log:
  console:
    pattern: '%highlight([%-5level]):%green([${spring.profiles.active}]):%yellow([%d{yyyy-MM-dd HH:mm:ss.SSS}])[%t]%cyan([%c{1}]):[%green(%line)]:[%green(%X{requestId})]:[%green(%X{sessionId})]:[%green(%X{username})]:%boldMagenta(%X{path}) - %m %n'
    level: INFO
    enable: true
  file:
    enable: true
    pattern: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] - [%X{requestId}] [%X{username}] [%X{path}] %msg%n%exception'
    path: {path-save-log}
    level: INFO
    size: 20MB
    max-history: 90
    total-size-cap: 1000
logging:
  level:
    vn:
      vnpay: INFO
    org:
      apache:
        kafka: WARN
