spring:
  datasource:
    online:
      enable: true
      jdbc-url: jdbc:oracle:thin:@192.168.74.106:1521/qd2345
      username: n4u25PZVtAisUleoYUTfMLyYnDHWJcXXPus=
      password: TS+VLrGqHQf7lTUdm5rbjFrOq0E25Nakr/giQw==
      driver-class-name: oracle.jdbc.OracleDriver
      pool-name: hikari-omni
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 10
      package-scan: vn.vnpay.*
    offline:
      enable: false