server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: file:/home/ebanking/scb-config-service/config-repo